export enum EventsTypes {
    EVENTS_LOAD = 'EVENTS_LOAD',
    EVENTS_LOAD_SUCCESS = 'EVENTS_LOAD_SUCCESS',
    EVENTS_LOAD_ERROR = 'EVENTS_LOAD_ERROR',
    EVENT_DELETE = 'EVENT_DELETE',
    EVENT_DELETE_SUCCESS = 'EVENT_DELETE_SUCCESS',
    EVENT_DELETE_ERROR = 'EVENT_DELETE_ERROR',
}
